### ISSUE TITLE
Box2D Setup in Android Studio

### ISSUE THREAD

**Issue by yaswant2403** [CS196Illinois/Group30-FA22#1]
Install Android Studio Here: https://developer.android.com/studio

**For Windows: ** Just Click Download for Windows

**For Mac: ** Download the version that's compatible with your device (Mac with Intel Chip or Mac with Apple Chip)
  It should highlight green the version you're compatible with automatically

Once installed, open Android Studio and it should take you to this screen:

![Image](https://user-images.githubusercontent.com/51063116/194465608-1685f2a8-7519-4cf2-bd5d-8cac1da20533.png)

**NEXT** follow the instructions in this video STEP BY STEP:

[Video Link](https://uofi.box.com/s/ca0tahr4mc1s1b3aa5dxyjl78pm210eo)

I'll be using this as my reference: https://libgdx.com/wiki/start/project-generation

**Comment by OBERATAR000** [comment]
DONE
